[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ˜¡ Nint"
ruleset = ""

[[rulesets]]
group = "ğŸŒ©ï¸ XunLei"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸ›‘ BanAD"
ruleset = ""

[[rulesets]]
group = "ğŸƒ BanProgramAD"
ruleset = ""

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = ""

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¢ Google"
ruleset = ""

[[rulesets]]
group = "ğŸ“¹ Youtube"
ruleset = ""

[[rulesets]]
group = "â“‚ï¸ OneDrive"
ruleset = ""

[[rulesets]]
group = "â“‚ï¸ Microsoft"
ruleset = ""

[[rulesets]]
group = "ğŸ Apple"
ruleset = ""

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = ""

[[rulesets]]
group = "ğŸ® Game"
ruleset = ""

[[rulesets]]
group = "ğŸ® Game"
ruleset = ""

[[rulesets]]
group = "ğŸ® Game"
ruleset = ""

[[rulesets]]
group = "ğŸ® Game"
ruleset = ""

[[rulesets]]
group = "ğŸ¥ Netflix"
ruleset = ""

[[rulesets]]
group = "ğŸ¥ Netflix"
ruleset = ""

[[rulesets]]
group = "ğŸ¥ Netflix"
ruleset = ""

[[rulesets]]
group = "ğŸ“º Bahamut"
ruleset = ""

[[rulesets]]
group = "ğŸ“º Iqiyi"
ruleset = ""

[[rulesets]]
group = "ğŸ“º Iqiyi"
ruleset = ""

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = ""

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = ""

[[rulesets]]
group = "ğŸŒ ChinaMedia"
ruleset = ""

[[rulesets]]
group = "ğŸŒ ProxyMedia"
ruleset = ""

[[rulesets]]
group = "ğŸ‡¿ ZhiHu"
ruleset = ""

[[rulesets]]
group = "ğŸ¦ Twitter"
ruleset = ""

[[rulesets]]
group = "ğŸ‡» Wechat"
ruleset = ""

[[rulesets]]
group = "ğŸª™ Binance"
ruleset = ""

[[rulesets]]
group = "ğŸš€ Proxy"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸ¯ Global"
ruleset = ""

[[rulesets]]
group = "ğŸŸ Final"
ruleset = ""

