[[rulesets]]
group = "ğŸ˜¡ Nint"
test = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/nint.list"

[[rulesets]]
group = "ğŸŒ©ï¸ XunLei"
test = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xunlei/Xunlei.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ›‘ BanAD"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸƒ BanProgramAD"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ† AdBlock"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"

[[rulesets]]
group = "ğŸ† AdBlock"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "[]DOMAIN-SUFFIX,services.googleapis.cn"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list"

[[rulesets]]
group = "ğŸ“¢ Google"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"

[[rulesets]]
group = "ğŸ“¹ Youtube"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "â“‚ï¸ OneDrive"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"

[[rulesets]]
group = "â“‚ï¸ Microsoft"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ Apple"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ“² Telegram"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ® Game"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ® Game"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® Game"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"

[[rulesets]]
group = "ğŸ® Game"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ¥ Netflix"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"

[[rulesets]]
group = "ğŸ¥ Netflix"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list"

[[rulesets]]
group = "ğŸ¥ Netflix"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list"

[[rulesets]]
group = "ğŸ“º Bahamut"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "ğŸ“º Iqiyi"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/IqiyiHMT.list"

[[rulesets]]
group = "ğŸ“º Iqiyi"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Iqiyi.list"

[[rulesets]]
group = "ğŸ“º Bilibili"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ“º Bilibili"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸŒ ChinaMedia"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸŒ ProxyMedia"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸ‡¿ ZhiHu"
test = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Zhihu/Zhihu.list"

[[rulesets]]
group = "ğŸ¦ Twitter"
test = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"

[[rulesets]]
group = "ğŸ‡» Wechat"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wechat.list"

[[rulesets]]
group = "ğŸª™ Binance"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Binance.list"

[[rulesets]]
group = "ğŸš€ Proxy"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "ğŸ¯ Global"
test = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ Final"
test = "[]FINAL"
